INSERT INTO USER (USER_ID, USERNAME, FIRST_NAME, LAST_NAME, GENDER, CONTRASENA) VALUES (1,'user1','ines','saavedra','Female', '{noop}123');
INSERT INTO USER (USER_ID, USERNAME, FIRST_NAME, LAST_NAME, GENDER,CONTRASENA ) VALUES (2,'beatriz24','beatriz','sicilia','Female', '{bcrypt}45678');
INSERT INTO USER (USER_ID, USERNAME, FIRST_NAME, LAST_NAME, GENDER,CONTRASENA ) VALUES (3,'breton88','jorge','breton','Male', '66666');

INSERT INTO PERIODO (PERIODO_CODE, USERNAME, NOMBRE_PERIODO, MES ) VALUES (4, 'user1', 'Verano', 'Julio');
INSERT INTO PERIODO (PERIODO_CODE, USERNAME, NOMBRE_PERIODO, MES ) VALUES (5, 'user1', 'Primavera', 'Abril');
INSERT INTO PERIODO (PERIODO_CODE, USERNAME, NOMBRE_PERIODO, MES ) VALUES (6, 'user1', 'Invierno', 'Enero');

INSERT INTO PERIODO (PERIODO_CODE, USERNAME, NOMBRE_PERIODO, MES ) VALUES (7, 'beatriz24', 'Invierno', 'Diciembre');
INSERT INTO PERIODO (PERIODO_CODE, USERNAME, NOMBRE_PERIODO, MES ) VALUES (8, 'beatriz24', 'Primavera', 'Mayo');
INSERT INTO PERIODO (PERIODO_CODE, USERNAME, NOMBRE_PERIODO, MES ) VALUES (9, 'beatriz24', 'Verano', 'Agosto');

INSERT INTO PERIODO (PERIODO_CODE, USERNAME, NOMBRE_PERIODO, MES ) VALUES (10, 'breton88', 'Verano', 'Julio');
INSERT INTO PERIODO (PERIODO_CODE, USERNAME, NOMBRE_PERIODO, MES ) VALUES (11, 'breton88', 'Invierno', 'Diciembre');
INSERT INTO PERIODO (PERIODO_CODE, USERNAME, NOMBRE_PERIODO, MES ) VALUES (12, 'breton88', 'Primavera', 'Marzo');


INSERT INTO GASTO (ID_GASTO, USERNAME, NOMBRE_PERIODO, CONCEPTO, IMPORTE, FECHA) VALUES (1,'ines21','Verano','Comida restaurante abc', 120.50, '2022-07-15');
INSERT INTO GASTO (ID_GASTO, USERNAME, NOMBRE_PERIODO, CONCEPTO, IMPORTE, FECHA) VALUES (2,'ines21','Primavera','hola', 110.50, '2021-07-15');
INSERT INTO GASTO (ID_GASTO, USERNAME, NOMBRE_PERIODO, CONCEPTO, IMPORTE, FECHA) VALUES (3,'ines21','Invierno','Comida restaurante el jueves', 12000.50, '2022-07-15');
INSERT INTO GASTO (ID_GASTO, USERNAME, NOMBRE_PERIODO, CONCEPTO, IMPORTE, FECHA) VALUES (4,'ines21','Primavera','Subscripcion para adultos', 10.50, '2021-07-15');
INSERT INTO GASTO (ID_GASTO, USERNAME, NOMBRE_PERIODO, CONCEPTO, IMPORTE, FECHA) VALUES (5,'ines21','Invierno','Asuntos personales', 120.50, '2022-07-15');
INSERT INTO GASTO (ID_GASTO, USERNAME, NOMBRE_PERIODO, CONCEPTO, IMPORTE, FECHA) VALUES (6,'ines21','Verano','Compañia', 101.50, '2021-07-15');

INSERT INTO GASTO (ID_GASTO, USERNAME, NOMBRE_PERIODO, CONCEPTO, IMPORTE, FECHA) VALUES (7,'breton88','Verano','Comida restaurante abc', 120.50, '2022-07-15');
INSERT INTO GASTO (ID_GASTO, USERNAME, NOMBRE_PERIODO, CONCEPTO, IMPORTE, FECHA) VALUES (8,'breton88','Primavera','hola', 110.50, '2021-07-15');
INSERT INTO GASTO (ID_GASTO, USERNAME, NOMBRE_PERIODO, CONCEPTO, IMPORTE, FECHA) VALUES (9,'breton88','Invierno','Comida restaurante el jueves', 12000.50, '2022-07-15');
INSERT INTO GASTO (ID_GASTO, USERNAME, NOMBRE_PERIODO, CONCEPTO, IMPORTE, FECHA) VALUES (10,'breton88','Primavera','Subscripcion para adultos', 10.50, '2021-07-15');
INSERT INTO GASTO (ID_GASTO, USERNAME, NOMBRE_PERIODO, CONCEPTO, IMPORTE, FECHA) VALUES (11,'breton88','Invierno','Asuntos personales', 120.50, '2022-07-15');
INSERT INTO GASTO (ID_GASTO, USERNAME, NOMBRE_PERIODO, CONCEPTO, IMPORTE, FECHA) VALUES (12,'breton88','Verano','Compañia', 101.50, '2021-07-15');

INSERT INTO GASTO (ID_GASTO, USERNAME, NOMBRE_PERIODO, CONCEPTO, IMPORTE, FECHA) VALUES (13,'beatriz24','Verano','Comida restaurante abc', 120.50, '2022-07-15');
INSERT INTO GASTO (ID_GASTO, USERNAME, NOMBRE_PERIODO, CONCEPTO, IMPORTE, FECHA) VALUES (14,'beatriz24','Primavera','hola', 110.50, '2021-07-15');
INSERT INTO GASTO (ID_GASTO, USERNAME, NOMBRE_PERIODO, CONCEPTO, IMPORTE, FECHA) VALUES (15,'beatriz24','Invierno','Comida restaurante el jueves', 12000.50, '2022-07-15');
INSERT INTO GASTO (ID_GASTO, USERNAME, NOMBRE_PERIODO, CONCEPTO, IMPORTE, FECHA) VALUES (16,'beatriz24','Primavera','Subscripcion para adultos', 10.50, '2021-07-15');
INSERT INTO GASTO (ID_GASTO, USERNAME, NOMBRE_PERIODO, CONCEPTO, IMPORTE, FECHA) VALUES (17,'beatriz24','Invierno','Asuntos personales', 120.50, '2022-07-15');
INSERT INTO GASTO (ID_GASTO, USERNAME, NOMBRE_PERIODO, CONCEPTO, IMPORTE, FECHA) VALUES (18,'beatriz24','Verano','Compañia', 101.50, '2021-07-15');

INSERT INTO CONTACTOS (ID_CONTACTO, USERNAME, NOMBRE, APELLIDO, MAIL, DIRECCION) VALUES (1,'beatriz24','Benito','Camela', 'vetageta@gmai.com', 'El valle de los caidos');
INSERT INTO CONTACTOS (ID_CONTACTO, USERNAME, NOMBRE, APELLIDO, MAIL, DIRECCION) VALUES (2,'beatriz24','Tomas','Camela', 'willyrex96@gmail.com', 'El valle de los perdidos');
INSERT INTO CONTACTOS (ID_CONTACTO, USERNAME, NOMBRE, APELLIDO, MAIL, DIRECCION) VALUES (3,'ines21','Jaime','Camela', 'jajaj@gmail.com', 'El valle de los enamorados');
INSERT INTO CONTACTOS (ID_CONTACTO, USERNAME, NOMBRE, APELLIDO, MAIL, DIRECCION) VALUES (4,'ines21','Palomo','Camela', 'apruebame@gmail.com', 'El valle de los enfadados');
INSERT INTO CONTACTOS (ID_CONTACTO, USERNAME, NOMBRE, APELLIDO, MAIL, DIRECCION) VALUES (5,'breton88','Eugenio','Camela', 'soycalvo@gmail.com', 'El valle de los ganadores');


INSERT INTO EVENTOS (ID_EVENTO, USERNAME, NOMBRE, DESCRIPCION, MES) VALUES (1,'beatriz24','San Fermin','Momento algido de la noche', 'Julio');
INSERT INTO EVENTOS (ID_EVENTO, USERNAME, NOMBRE, DESCRIPCION, MES) VALUES (2,'ines21','SuaveFest','la maria pombo', 'Mayo');
INSERT INTO EVENTOS (ID_EVENTO, USERNAME, NOMBRE, DESCRIPCION, MES) VALUES (3,'breton88','StarLite','va Victoria', 'Julio');
