
DROP TABLE IF EXISTS USER;
/*DROP TABLE IF EXISTS GRUPO; 
*/
DROP TABLE IF EXISTS PERIODO; 

DROP TABLE IF EXISTS GASTO; 
DROP TABLE IF EXISTS CONTACTOS; 

DROP TABLE IF EXISTS EVENTOS; 


CREATE TABLE USER (
  USER_ID int(11) NOT NULL AUTO_INCREMENT,
  USERNAME varchar(255) DEFAULT NULL,
  FIRST_NAME varchar(50) DEFAULT NULL,
  LAST_NAME varchar(50) DEFAULT NULL,
  GENDER varchar(10) DEFAULT NULL,
  CONTRASENA varchar(255) DEFAULT NULL,
  PRIMARY KEY (USER_ID)
);



CREATE TABLE PERIODO(
  PERIODO_CODE int(11) NOT NULL AUTO_INCREMENT,
  USERNAME varchar(255) DEFAULT NULL,
  NOMBRE_PERIODO VARCHAR2(40) NOT NULL,
  MES VARCHAR2(40) NOT NULL,
  PRIMARY KEY (PERIODO_CODE)
); 


/*

CREATE TABLE GRUPO(
  GRUPO_CODE int(11) NOT NULL AUTO_INCREMENT,
  USERNAME varchar(255) DEFAULT NULL,
  NOMBRE_PERIODO VARCHAR2(40) DEFAULT NULL,
  NOMBRE_GRUPO VARCHAR2(40) NOT NULL,
  FOTO VARCHAR2(255),
  PRIMARY KEY (GRUPO_CODE)
); 
*/

CREATE TABLE GASTO(
  ID_GASTO  int(11) NOT NULL AUTO_INCREMENT,
  USERNAME varchar(255) DEFAULT NULL,
  NOMBRE_PERIODO VARCHAR2(40) NOT NULL,
  CONCEPTO VARCHAR2(40) NOT NULL,
  IMPORTE FLOAT NOT NULL,
  FECHA DATE NOT NULL,
  PRIMARY KEY(ID_GASTO)
); 

CREATE TABLE CONTACTOS(
  ID_CONTACTO  int(11) NOT NULL AUTO_INCREMENT,
  USERNAME varchar(255) DEFAULT NULL,
  NOMBRE VARCHAR2(40) NOT NULL,
  APELLIDO VARCHAR2(40) NOT NULL,
  MAIL VARCHAR2(40) NOT NULL,
  DIRECCION VARCHAR2(40) NOT NULL,
  PRIMARY KEY(ID_CONTACTO)
);


CREATE TABLE EVENTOS(
  ID_EVENTO  int(11) NOT NULL AUTO_INCREMENT,
  USERNAME varchar(255) DEFAULT NULL,
  NOMBRE VARCHAR2(40) NOT NULL,
  DESCRIPCION VARCHAR2(40) NOT NULL,
  MES VARCHAR2(40) NOT NULL,
  PRIMARY KEY(ID_EVENTO)
)

